name: CD

on:
  release:
    types: [ published ]

jobs:
  cd:
    permissions:
      contents: write
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@v5
    secrets:
      halo-pat: ${{ secrets.HALO_PAT }}
    with:
      app-id: app-qjw66wdx
      java-version: 21
      skip-node-setup: true
