name: CD

on:
  release:
    types: [ published ]

jobs:
  cd:
    permissions:
      contents: write
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@v3
    with:
      java-version: 21
      skip-node-setup: true
      skip-appstore-release: true
